[package]
name = "nvtop"
version = "0.1.3"
edition = "2024"
description = """ nvtop: An NVIDIA SMI'esk GPU Monitoring tool for your terminal. """
keywords = [
  "Real-time monitoring",
  "GPU",
  "NVIDIA",
  "nvml",
  "nvidia-smi",
  "Command-line tool",
]
authors = ["jer, alphastrata@gmail.com", "camuward, cameronuward@gmail.com"]
documentation = "https://www.github.com/alphastrata/nvtop-rust"
license = "MIT"
homepage = "https://www.jeremyfwebb.ninja"
publish = true

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["derive"] }
crossterm = "0.29.0"
nvml-wrapper = "0.11.0"
ratatui = "0.30.0"
skim = "0.10.4"
thiserror = "2.0.18"
